### ISSUE TITLE
Status Error 404 while fetching gldas data

### ISSUE THREAD

**Issue by subimalnandi** [c-h-david/shbaam#12] opened 2021-03-03 12:33 UTC
In the beginning of gldas data download step. 
I am facing status Error 404 
Then I checked code and went to the link it is removed.
Please help me

**Comment by c-h-david** [comment] 2021-03-03 15:53
Duplicate of #11. 
I welcome your help if you're able to locate where GLDAS1 data can be downloaded from NASA's GES-DISC or NASA's EarthData.

**Closed as completed by c-h-david** 2021-03-03 15:53 UTC

**Comment by subimalnandi** [comment] 2021-03-08 08:31
https://ldas.gsfc.nasa.gov/gldas/news/gldas-1-products-will-be-decomissioned-6302020
GLDAS-1 Products Will Be Decomissioned On 6/30/2020
With the upgraded Land Surface Models (LSMs) and updated forcing data sets, the GLDAS-2.1 production stream serves as a replacement for GLDAS-1.  Therefore, the GLDAS-1 production stream will end with the March 2020 data.  The entire collection will be aviable at the GES DISC until June 30, 2020.
[README_GLDAS2.pdf](https://github.com/c-h-david/shbaam/files/6100238/README_GLDAS2.pdf)

**Comment by subimalnandi** [comment] 2021-03-08 09:00
https://hydro1.gesdisc.eosdis.nasa.gov/data/GLDAS/
CLM model is replaced by CLSM while there is no data for MOSAIC model. Only NOAH and VIC are available there. for GLDAS 2.1


Thank you for your reply
